[package]
name = "katsuo-ropebound"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

# Apply all optimiations to dependencies in dev builds
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version= "0.16.1", features=["wayland"] }
bevy_sprite = "0.16.1"
rand = "0.9.2"
